version: '3'

services:
    
    django:
        image : sogloarcadius/portfolio-backend:https
        environment:
            - SYSLOG_HOST
            - SYSLOG_PORT
            - JWT_EXPIRATION_DELAY
            - JWT_ISSUER
            - JWT_PUBLIC_KEY
            - JWT_PRIVATE_KEY
        build: 
            context: .
            dockerfile: ./Dockerfile.https
            args:
                - SYSLOG_HOST
                - SYSLOG_PORT
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /docker/portfolio/volumes/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
            - /docker/portfolio/volumes/etc/letsencrypt/live/sogloarcadius.fr/fullchain.pem:/etc/letsencrypt/live/sogloarcadius.fr/fullchain.pem
            - /docker/portfolio/volumes/etc/letsencrypt/live/sogloarcadius.fr/privkey.pem:/etc/letsencrypt/live/sogloarcadius.fr/privkey.pem
        depends_on:
            - syslog-ng
            - os-metrics
            - prometheus
            - grafana