version: '3'

services:

    django:
        image: sogloarcadius/portfolio-backend:httponly
        environment:
            - SYSLOG_HOST
            - SYSLOG_PORT
            - JWT_EXPIRATION_DELAY
            - JWT_ISSUER
            - JWT_PUBLIC_KEY
            - JWT_PRIVATE_KEY
        build: 
            context: .
            dockerfile: ./Dockerfile.httponly
            args:
                - SYSLOG_HOST
                - SYSLOG_PORT
        ports:
            - "80:80"
        depends_on:
            - syslog-ng
            - os-metrics
            - prometheus
            - grafana    