version: "3"

services:

  elk:
    image: sebp/elk:600
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      - ES_HEAP_SIZE=2g
      - LS_HEAP_SIZE=1g
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    
  filebeat:
    build:
      context: .
      dockerfile: ./docker/filebeat/Dockerfile
    volumes :
      - /var/log/:/var/log/
    depends_on:
      - elk

  letsencrypt:
    build:
      context: .
      dockerfile: ./docker/letsencrypt/Dockerfile
    ports:
      - "80:80"
    volumes:
      - /docker/portfolio/volumes/letsencrypt-data:/usr/share/nginx/html
