version: '3'

services:

    #letsencrypt certificate issuer
    letsencrypt:
        build:
            context: .
            dockerfile: ./DockerImages/letsencrypt/Dockerfile
        ports:
            - "80:80"
        volumes:
            - /docker/portfolio/volumes/letsencrypt-data:/usr/share/nginx/html
    #syslog
    log:
        build:
            context: .
            dockerfile: ./DockerImages/log/Dockerfile
        volumes :
            - /var/log:/var/log/
    
    #prometheus metrics
    metrics:
        build:
          context: .
          dockerfile: ./DockerImages/metrics/Dockerfile
        ports:
            - "9090:9090"
    
    #export metrics on host (cpu,memory,..)
    os-metrics:
        image : "prom/node-exporter"
        ports:
            - "9100:9100"  

    grafana:
        image: grafana/grafana
        ports:
            - "2048:3000"
        depends_on:
            - metrics

    #Elastic search + logstash + kibanna
    elk:
        build:
            context: .
            dockerfile: ./DockerImages/elk/Dockerfile
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
        environment:
            - ES_HEAP_SIZE=2g
            - LS_HEAP_SIZE=1g
            - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    
    #Parse Syslog and load into elastic search
    filebeat:
        build:
          context: .
          dockerfile: ./DockerImages/filebeat/Dockerfile
        volumes :
            - /var/log/:/var/log/
        depends_on:
            - elk
    
    app:
        image : soglomania/portfolio
        env_file: environment.properties
        build: .
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - log
            - metrics
            - os-metrics
        volumes:
            - /docker/portfolio/volumes/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
            - /docker/portfolio/volumes/etc/letsencrypt/live/sogloarcadius.com/fullchain.pem:/etc/letsencrypt/live/sogloarcadius.com/fullchain.pem
            - /docker/portfolio/volumes/etc/letsencrypt/live/sogloarcadius.com/privkey.pem:/etc/letsencrypt/live/sogloarcadius.com/privkey.pem    
    
    monitoring:
        build : .
        env_file: environment.properties
        depends_on:
            - elk
            - filebeat