version: '3'

services:
    #syslog
    log:
        build:
            context: .
            dockerfile: ./DockerImages/log/Dockerfile
        volumes :
            - /var/log:/var/log/
    
    #prometheus metrics
    metrics:
        build:
          context: .
          dockerfile: ./DockerImages/metrics/Dockerfile
        ports:
            - "9090:9090"
    
    #export metrics on host (cpu,memory,..)
    os-metrics:
        image : "prom/node-exporter"
        ports:
            - "9100:9100"  

    metrics-graph:
        image: grafana/grafana
        ports:
            - "3000:3000"
        depends_on:
            - metrics
    
    #Elastic search + logstash + kibanna
    elk:
        build:
            context: .
            dockerfile: ./DockerImages/elk/Dockerfile
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
        environment:
            - ES_HEAP_SIZE=2g
            - LS_HEAP_SIZE=1g
            - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"

        
    filebeat:
        build:
          context: .
          dockerfile: ./DockerImages/filebeat/Dockerfile
        volumes :
            - /var/log/:/var/log/
 
    main:
        image : soglomania/portfolio
        env_file: environment.properties
        build: .
        ports:
            - "80:80"
        depends_on:
            - log
            - metrics
            - os-metrics
            - metrics-graph
            - elk
            - filebeat